### PR TITLE
Reliable quadrant

### LINKED ISSUE #622: Finding quadrants is flawed
As pointed out here https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/621#discussion_r1469320240, the function `_quadrant` used internally for trigonometric functions may yield wrong results.

See https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/621#discussion_r1469423662 for a proposal to fix the issue (at least partially).

Also, this issue can be related to #129 on the implementation of `mod` for intervals (see also PR #145 and #178).

### PR DESCRIPTION
**Pull request by OlivierHnt**
This PR implements a reliable code to determine quadrants for trigonometric functions.

@dpsanders do you mind having a look?

Closes #622

### CODE REVIEW

File: src/intervals/arithmetic/trigonometric.jl [hunk 1]
```diff
@@ -65,8 +68,8 @@ function Base.sin(x::BareInterval{T}) where {T<:AbstractFloat}
 
     lo, hi = bounds(x)
 
-    lo_quadrant = _quadrant(lo)
-    hi_quadrant = _quadrant(hi)
+    lo_quadrant = _quadrant(min, lo)
```
Comment (dpsanders) [inline src/intervals/arithmetic/trigonometric.jl:71]: Why do you need the `min` and `max` here?

**Review by dpsanders — APPROVED** [review]
LGTM as far as I can tell, thanks!

File: src/intervals/arithmetic/trigonometric.jl (hunk 1 above)
Comment (OlivierHnt) [reply src/intervals/arithmetic/trigonometric.jl:71]: `_quadrant` may return two distinct integers. What `min`/`max` aims to do is to "overshoot" the quadrants: for the lowest (resp. largest) value of the interval, we want the smallest (resp. largest) quadrant.
