### PR TITLE
1.0-dev: improve printing and fix alignment issue

### LINKED ISSUE #316: BigFloat output incorrect for large exponents
```jl
julia> IntervalArithmetic.atomic(Interval{BigFloat}, -Inf)
[-∞, -5.87565e+1388]₂₅₆

julia> prevfloat(big(Inf))
5.875653789111587590936911998878442589938516392745498308333779606469323584389875e+1388255822130839282
```
The exponent in the interval display is wrong (truncated).

cc @yashrajgupta

### LINKED ISSUE #434: Fix printing of matrices of intervals
```jl
julia> M = [1.2..1.6 1.2..1.6; -1..1 -1..1]
2×2 Array{Interval{Float64},2}:
      [1.19999, 1.60001]       [1.19999, 1.60001]
 [-1, 1]                  [-1, 1]
```

### PR DESCRIPTION
**Pull request by OlivierHnt**
Over the week-end I experimented with the printing mechanism of the 1.0-dev branch. This is the resulting PR 🙂.

Fix #316, #434.

It seems that the alignment issue when printing arrays is linked to the fact that `Interval <: Real` and sometimes the bounds of the intervals are printed with no decimal points. The current behaviour (before this PR) relies on the format `"%.g"` which gives the shortest form for a given number (e.g. `1.0` would be returned as `1`).

So this would explain also why `IntervalBox` had no printing issues: it is not a subtype of `Real`.

In this PR I tried to stay as close as possible to the current behaviour, so the only **visual change** is that exact integers are displayed with a trailing decimal point and 0, for instance `1` is printed as `1.0`.
I have modified the tests to comply with this change.

Before this PR:

```julia
julia> M = [1.2..1.6 1.2..1.6; -1..1 -1..1]  # format === :standard
2×2 Matrix{Interval{Float64}}:
      [1.19999, 1.60001]       [1.19999, 1.60001]
 [-1, 1]                  [-1, 1]

julia> M = [1.2..1.6 1.2..1.6; -1..1 -1..1]  # format === :midpoint
2×2 Matrix{Interval{Float64}}:
     1.4 ± 0.200001      1.4 ± 0.200001
 0 ± 1               0 ± 1
```

After this PR:

```julia
julia> M = [1.2..1.6 1.2..1.6; -1..1 -1..1]  # format === :standard
2×2 Matrix{Interval{Float64}}:
  [1.19999, 1.60001]   [1.19999, 1.60001] # expected shift to the right to account for potential minus signs `-`
 [-1.0, 1.0]          [-1.0, 1.0]

julia> M = [1.2..1.6 1.2..1.6; -1..1 -1..1]  # format === :midpoint
2×2 Matrix{Interval{Float64}}:
 1.4 ± 0.200001  1.4 ± 0.200001
 0.0 ± 1.0       0.0 ± 1.0
```

### Other changes

- There was only one test which did not pass but I think it is wrong.
Before this PR:
```julia
string(2.1..2.2) == [2.1, 2.20001]   # seems wrong, no?
```
After this PR:
```julia
string(2.1..2.2) == [2.09999, 2.20001]
```

- I uncommented some tests for `Complex{<:Interval}`, they pass successfully. In the file changelog.md, it is mentioned that support for `Complex{<:Interval}` is dropped 🙁. However, there are still existing functionalities for `Complex{<:Interval}` on this branch and the display tests pass without extra work.

- Rename the keyword argument `sigfigs`  of `setformat` to `sigdigits` to match the naming convention of Julia (e.g. see the keywords of `round`).

- Fix all the inconsistencies where `==` was used instead of `===` (or `!=` instead of `!==`). In particular, use `===` to compare symbols.

- Improve performance of printing. For instance, faster `supscriptify` and `subscriptify` and `representation` is now type-stable.

For instance, before this PR:

```julia
julia> @btime IntervalArithmetic.subscriptify($8);
  135.643 ns (6 allocations: 352 bytes)

julia> @btime IntervalArithmetic.subscriptify($111);
  202.847 ns (7 allocations: 464 bytes)

julia> @btime IntervalArithmetic.supscriptify($8);
  148.988 ns (7 allocations: 448 bytes)

julia> @btime IntervalArithmetic.supscriptify($111);
  178.257 ns (7 allocations: 496 bytes)
```

After this PR:

```julia
julia> @btime IntervalArithmetic.supscriptify($8);  # Same timing for subscriptify
  3.666 ns (0 allocations: 0 bytes)

julia> @btime IntervalArithmetic.supscriptify($111);  # Same timing for subscriptify
  107.967 ns (4 allocations: 240 bytes)
```

### CODE REVIEW

File: src/display.jl [hunk 1]
```diff
@@ -1,379 +1,405 @@
...
+# Printing mechanism for various types of intervals
 
-if VERSION < v"1.1.0-DEV.683"
-    to_mpfr(r) = Base.MPFR.to_mpfr(r)
-else
-    to_mpfr(r) = convert(Base.MPFR.MPFRRoundingMode, r)
-end
-
-## Output
+show(io::IO, a::Union{Interval,Complex{<:Interval},DecoratedInterval,IntervalBox}) =
```
Comment (Kolaru) [inline src/display.jl:142]: Should this be general or only define for `MIME"text/plain"` This also overrides `repr` which is [kind of](https://docs.julialang.org/en/v1/base/strings/#Base.repr-Tuple%7BAny%7D) expected to return a string that can be copy pasted back into julia and work.

Then an even more specific method could be defined for the `:compact:` case, when intervals are printed inside an array.

@lucaferranti @lbenet 

(note that this is also not central to the PR, and can be left for another one)

File: test/display_tests/display.jl [hunk 2]
```diff
@@ -81,58 +81,56 @@ let x, b
...
 
-        setformat(decorations=false)
+        setformat(; decorations = false)
         @test string(a) == "2.5 ± 0.5"
 
     end
 
     setprecision(BigFloat, 128)
 
     @testset "BigFloat intervals" begin
```
Comment (Kolaru) [inline test/display_tests/display.jl:128]: Unless I missed it, can you add the example from #316 to be sure it works now (and that it will continue to work).

**Review by Kolaru — CHANGES_REQUESTED** [review]
Very nice job overall, I'm very thankful you decided to delve into this!

Also thanks very much for the informative comments and docstrings.

File: src/display.jl [hunk 3]
```diff
@@ -1,379 +1,405 @@
...
+    i == 0 && return "₀"
+    i == 1 && return "₁"
+    i == 2 && return "₂"
+    i == 3 && return "₃"
+    i == 4 && return "₄"
+    i == 5 && return "₅"
+    i == 6 && return "₆"
+    i == 7 && return "₇"
+    i == 8 && return "₈"
+    return "₉"
```
Comment (lucaferranti) [inline src/display.jl:404]: I would also include the

```julia
i == 9 && return "₉"
```

and throw an exception as fallback. Might be a little overcautious, but if somehow you get an invalid integer and the printing silently,identifying the bug might be a little tricky

**Review by lucaferranti — DISMISSED** [review]

File: src/display.jl [hunk 4]
```diff
@@ -1,379 +1,405 @@
 mutable struct DisplayParameters
```
[the remark this answers is not in the document]
Comment (OlivierHnt) [reply src/display.jl:1]: Indeed, I removed the extra spacing.

File: src/display.jl [hunk 5]
```diff
@@ -1,379 +1,405 @@
...
+  - decorations: true
+  - significant digits: 3
 
-julia> x
-[0.0999, 0.301]
+julia> y
+[0.0999, 0.301]_com
 ```
 """
 macro format(expr...)
```
[the remark this answers is not in the document]
Comment (OlivierHnt) [reply src/display.jl:119]: I reverted this change. You are right that it may be better to have a specific PR targeting docstrings.

About the proposition to remove `@format`: I also fail to see why `@format` is more convenient than just calling `setformat` directly. I can make a PR suggesting to remove it.

File: test/display_tests/display.jl (hunk 2 above)
Comment (OlivierHnt) [reply test/display_tests/display.jl:135]: I added the requested tests.

File: src/display.jl (hunk 3 above)
Comment (OlivierHnt) [reply src/display.jl]: That's a good point. Done.

File: src/display.jl (hunk 1 above)
Comment (OlivierHnt) [reply src/display.jl]: Interesting. I just tried this and I think it is a nice change. As an added benefit, this allows us to remove `showfull` entirely since `show(:Interval)` now has this behaviour.

**Comment by OlivierHnt** [comment]
@Kolaru @lucaferranti
Thank you for the feedback on this PR! 🙂 

I have made the requested changes.

The commit [cbbd9ed](https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/555/commits/cbbd9edab4c5b00d4265b6b0824620eb06142e0d) (which introduces tests for large exponents) revealed that the printing of large exponent changes depending on the OS, e.g. Windows. Since I work on macOS, I did not see this issue.
Does anyone know what could be the cause? An issue with how `BigFloat` is handled?

Moreover, the two last commits are worth discussing. The commit [f66abd1](https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/555/commits/f66abd11007b4224b81d09656bcab7f134fe8a2e) defines `show` on `::MIME"text/plain"` as suggested by @Kolaru. The default `show` with no `MIME` checks for `:compact` in which case it will behave as `::MIME"text/plain"` (in particular, this ensures that we have nice printing for matrices).
Doing this makes `show(::Interval)` behave exactly like `showfull`. So the commit [d2418e3](https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/555/commits/d2418e3e0a6282f58709e2dbfdafa4b5fec42523) removes `showfull`.
N.B.: now `string(::Interval)` returns a string which looks like the output of `show(::Interval)`, which feels like the right thing.

**Comment by Kolaru** [comment]
> The commit [cbbd9ed](https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/555/commits/cbbd9edab4c5b00d4265b6b0824620eb06142e0d) (which introduces tests for large exponents) revealed that the printing of large exponent changes depending on the OS, e.g. Windows. Since I work on macOS, I did not see this issue.
> Does anyone know what could be the cause? An issue with how `BigFloat` is handled?

Oh no. This is concerning, I will try to reproduce locally (I've access to linux and windows) and see if can understand where it comes from.

> N.B.: now `string(::Interval)` returns a string which looks like the output of `show(::Interval)`, which feels like the right thing.

I think it feels right as well, but we need to check if the IEEE standard as an opinion about representing intervals as string. Worst case we need an additional specific method to have the output prescribed by the standard.

**Comment by OlivierHnt** [comment]
> Oh no. This is concerning, I will try to reproduce locally (I've access to linux and windows) and see if can understand where it comes from.

Thanks for looking into this!

> I think it feels right as well, but we need to check if the IEEE standard as an opinion about representing intervals as string. Worst case we need an additional specific method to have the output prescribed by the standard.

I just had a look at the standard and, as far as I can tell, they only specify "interval literals" for parsing purposing. So the meaning of the function `string` from Base does not seem to be conflicting (in fact, it is kind of better now because the output of `string` is now valid code to construct the exact interval).
Perhaps @lucaferranti could double-check this since he seems well versed with the standard? 🙂

**Comment by lucaferranti** [comment]
sorry for the very slow follow-up. I am in a very busy couple of weeks, with several paper deadlines approaching.

I'll try to double check the discussion today

**Comment by Kolaru** [comment]
I checked and the test are passing on my CentOS machine. So I'm very confused.

I will run the tests with the PR on my windows machine tonight.

**Comment by Kolaru** [comment]
This is a platform depend behavior (bug ?) of BigFloat. I reported it there https://github.com/JuliaLang/julia/issues/48678.

On Windows:
```julia
julia> big"-5.87565e+1388255822130839282"
-Inf
```

On Ubuntu (WSL):
```julia
julia> big"-5.87565e+1388255822130839282"
-5.875649999999999999999999999999999999999999999999999999999999999999999999999983e+1388255822130839282
```

For now I think it would be good enough to test with a slightly less crazy bound like `1e123456789`.

**Comment by OlivierHnt** [comment]
Thanks @Kolaru for looking into this! The CI now runs successfully with the smaller exponent that you suggested 🎉

File: src/display.jl [hunk 6]
```diff
@@ -1,379 +1,405 @@
...
+    println(io, "Display options:")
+    println(io, "  - format: ", params.format)
+    println(io, "  - decorations: ", params.decorations)
+    print(io, "  - significant digits: ", params.sigdigits)
 end
 
-const display_params = DisplayParameters(:standard, false, 6)
-
-const display_options = (:standard, :full, :midpoint)
+const display_params = DisplayParameters(:standard, false, 6)  # Default
```
Comment (lbenet) [inline src/display.jl:14]: What about displaying by default the decoration? If you care about `DecoratedIntervals`, you want to see it!

File: test/display_tests/display.jl [hunk 7]
```diff
@@ -8,235 +8,238 @@ let x, b
...
+        @test sprint(show, MIME("text/plain"), a) == "[2.0, 3.0]₁₂₈"
 
-        setformat(:standard, decorations=true)
-        @test string(a) == "[2, 3]₁₂₈_com"
+        setformat(:standard; decorations = true)
+        @test sprint(show, MIME("text/plain"), a) == "[2.0, 3.0]₁₂₈_com"
 
         setformat(:full)
-        @test string(a) == "DecoratedInterval(Interval(2.0, 3.0), com)"
+        @test sprint(show, MIME("text/plain"), a) == "DecoratedInterval(Interval(2.0, 3.0), com)"
```
Comment (lbenet) [inline test/display_tests/display.jl:162]: This is a comment/suggestion, which I guess is small enough to be incorporated for intervals/decorated intervals with `BigFloat`s: I like that the `:standard` format shows the precision of the BigFloat end-points; this is not included in the `:full` format, as shown by this example. I think displaying the precision is informative; while we *usually* fix it (and forget it), MPFR allows to work with different precisions, which is a case where it is worth a reminder. 
So, what about including the precision for `Interval{BigFloat}` and `DecoratedInterval{BigFloat}` always?

Comment (OlivierHnt) [reply test/display_tests/display.jl:162]: It is not a bad idea. Note that we need a signature for `show` which returns parseable Julia code (cf. docstring for `show`). In this PR this behaviour is tied with the formatting mechanism via `setformat(:full)`.
I think the best option would be to add an other symbol, say `:raw` (or perhaps `:parseable` 🤷‍♂️ ), such that `setformat(:raw)` replaces the current`setformat(:full)`. Then, `setformat(:full)` can have the behaviour you suggest.

Also, do you have a display in mind? Something like `@biginterval(1)` is displayed as `"Interval(1.0, 1.0)₂₅₆"`?

File: src/display.jl (hunk 6 above)
Comment (OlivierHnt) [reply src/display.jl:14]: That is a good idea, I think that would be a nice improvement 🙂.

File: test/display_tests/display.jl (hunk 7 above)
Comment (OlivierHnt) [reply test/display_tests/display.jl:162]: For consistency, what about doing this for `:midpoint` as well?

So it would look like
```julia
julia> setformat(:midpoint)
Display options:
  - format: midpoint
  - decorations: true
  - significant digits: 6

julia> big(1)..2
(1.5 ± 0.5)₂₅₆

julia> setformat(:full);  # full display of the bounds and show precision if BigFloat

julia> big(1)..2
Interval(1.0, 2.0)₂₅₆

julia> setformat(:parseable);  # parseable Julia code

julia> big(1)..2
Interval(1.0, 2.0)
```

Comment (lbenet) [reply test/display_tests/display.jl:162]: Great that the comment was useful! 😄 

I like all proposals:
- the `:raw` and `:full` formats, where the raw format is for copy-paste (or saving results to be reused), and the full format is to have all details displayed;
- I like the display you propose `Interval(1.0, 1.0)₂₅₆`;
- include the precision in the `:midpoint` format.

Comment (OlivierHnt) [reply test/display_tests/display.jl:162]: But now I am not unsure about the `:raw`/`:parseable` options 🤔. Mainly because the way Julia gives information of the precision for `BigFloat` is through the function `precision` and not the display.
So showing `Interval{BigFloat}` is sufficient and consistent with Base. A user would know that they have an interval with bounds of type `BigFloat` which has precision `precision(BigFloat)`.

But it is definitely useful to display the precision for `:midpoint`. So I will add a commit for this.

**Comment by OlivierHnt** [comment]
In the last commit I have also changed the display of decorated intervals with the format `:midpoint`. Before `DecoratedInterval(1..2)` was displayed `1.5 ± 0.5_com`, now it is shown as `(1.5 ± 0.5)_com`.

**Review by Kolaru — APPROVED** [review]
Everything looks good to me, thanks a lot!

**Comment by lbenet** [comment]
LGTM too, so let's go ahead and merge this!

**Comment by lbenet** [comment]
Thanks a lot @OlivierHnt

File: src/display.jl (hunk 5 above)
[the remark this answers is not in the document]
Comment (OlivierHnt) [reply src/display.jl:119]: See PR #563.
